### ISSUE TITLE
Wireframes (1st iteration)

### ISSUE THREAD

**Issue by troyknatt** [kwong101/GameXchange#3]
# HOME PAGE: 
![IMG_9325](https://user-images.githubusercontent.com/38020368/81036212-1856e880-8e53-11ea-9a12-c1c3f3efd024.jpg)

# USER PAGE: 
![IMG_9326](https://user-images.githubusercontent.com/38020368/81036222-20168d00-8e53-11ea-8756-6570fc950869.jpg)

# LISTING PAGE:
![IMG_9327](https://user-images.githubusercontent.com/38020368/81036226-273d9b00-8e53-11ea-9a03-3934047d37c2.jpg)

# LOGIN/CREATE ACC PAGE:
![IMG_9328](https://user-images.githubusercontent.com/38020368/81036234-2efd3f80-8e53-11ea-9f17-f5b789e078b0.jpg)

# BROWSE PAGE:
![IMG_9329](https://user-images.githubusercontent.com/38020368/81036242-34f32080-8e53-11ea-96c8-a7343c69ce19.jpg)

# MESSAGE PAGE: 
![IMG_9330](https://user-images.githubusercontent.com/38020368/81036256-3f151f00-8e53-11ea-97b3-f94c9693003e.jpg)

**Comment by kwong101** [comment]
# HOME PAGE: 
![IMG_5957](https://user-images.githubusercontent.com/43554963/80854756-9dda5e80-8bef-11ea-90cb-0005117a7e33.jpg)

# USER PAGE:
![IMG_5958](https://user-images.githubusercontent.com/43554963/80854809-f3167000-8bef-11ea-850f-4998c2219292.jpg)

#LISTING PAGE:
![IMG_5959](https://user-images.githubusercontent.com/43554963/80854811-fb6eab00-8bef-11ea-9189-548398b3f816.jpg)

#LOGIN/CREATE ACC PAGE:
![IMG_5960](https://user-images.githubusercontent.com/43554963/80854816-03c6e600-8bf0-11ea-9961-827cb01f1349.jpg)

#BROWSE PAGE:
![IMG_5961](https://user-images.githubusercontent.com/43554963/80854822-09bcc700-8bf0-11ea-8325-b6c09dba436e.jpg)

MESSAGE PAGE:
![IMG_5962](https://user-images.githubusercontent.com/43554963/80854836-193c1000-8bf0-11ea-8dd2-1af0383486f3.jpg)
