### ISSUE TITLE
Create Listings Functionality

### ISSUE THREAD

**Issue by kwong101** [kwong101/GameXchange#32]
# STATUS = PARTIALLY COMPLETE

# How to create new listing: 

0. Should only be available upon log in 
1. Click on "Create Listing" in the top bar
2. Enter in information 
3. Information gets sent to listing database
![image](https://user-images.githubusercontent.com/43554963/98183721-a45ad300-1ebd-11eb-98ae-497665c2a043.png)

4. Upon "Post", user redirected to their new post page!!!
- should be listed under /listings/{listing_id} 

# THINGS THAT STILL NEED TO BE DONE

1. On the "Create Listing" page
- ~~need to enable image uploading~~
- ~~need to save uploaded image w/ product id in Image Schema~~
- ~~need to remove images field from create listing page~~
- ~~need to remove images field from listing schema~~

- ~~enable selection for categories (board game, cards, video game, other, etc.)~~
- ~~enable selection for condition ( worn, good, great, excellent, new)~~
- ~~enlarge size of description box~~
- ~~remove "owner" (should be auto filled in when logged in user is posting)~~

2. ~~Redirecting to new page once user clicks "post"~~

**Comment by troyknatt** [comment]
I created a browse component and a view-listing component. 

**browse component** 
- real ugly placeholder, but the main functionality is there. 
- Shows all listings we have in our DB
- Edit button works but not set up properly yet
- Delete button works, need to change permissions on the use of it though

**view-listing component**
- Now, going to http://localhost:3000/listings/{object id here} will show you information regarding that specific listing. 
- I had to make this component first, so I have somewhere to send the user after they click "post" when creating new listing.
