### ISSUE TITLE
Delete Listings Functionality 

### ISSUE THREAD

**Issue by kwong101** [kwong101/GameXchange#33]
# STATUS = NOT DONE 

# Steps
1. User clicks on "my listings" --> listings/owner={user_id here}
2. Click on "delete listing" button
- removes designated listing from database
3. User redirected to "my listings"

**Comment by troyknatt** [comment]
The delete button is functional now. Need to make changes to permissions, (like you can only delete your own posts) at a later time, but at least we know it works for sure.
