### ISSUE TITLE
Wireframes (2nd iteration)

### ISSUE THREAD

**Issue by troyknatt** [kwong101/GameXchange#4]

**Comment by kwong101** [comment]
# HOME PAGE:
![IMG_6016](https://user-images.githubusercontent.com/43554963/81270211-3bbe9680-8fff-11ea-83de-567a27a00def.jpg)

# PROFILE PAGE:
![IMG_6017](https://user-images.githubusercontent.com/43554963/81270238-4842ef00-8fff-11ea-87c3-595c0ab5d230.jpg)

# LISTINGE PAGE:
![IMG_6018](https://user-images.githubusercontent.com/43554963/81270254-50029380-8fff-11ea-8bae-0240612ceeea.jpg)

# LOGIN/SIGNUP PAGE
![IMG_6019](https://user-images.githubusercontent.com/43554963/81270266-55f87480-8fff-11ea-90d7-55067c564ff1.jpg)

# BROWSE PAGE:
![IMG_6020](https://user-images.githubusercontent.com/43554963/81270288-5ee94600-8fff-11ea-9d6c-e61b2211ab73.jpg)

# MESSAGE USERS:
![IMG_6021](https://user-images.githubusercontent.com/43554963/81270309-6577bd80-8fff-11ea-98dd-ff77072edc62.jpg)

**Comment by troyknatt** [comment]
# HOME PAGE:
![IMG_9357 1](https://user-images.githubusercontent.com/38020368/81476545-488de680-91c7-11ea-82ea-0494be8cbc45.JPG)

# USER PAGE:
![IMG_9358 1](https://user-images.githubusercontent.com/38020368/81476560-68250f00-91c7-11ea-8f5b-bab5ebdf266e.JPG)
